# Generated by Django 2.2.16 on 2022-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAndCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirm_code', models.CharField(max_length=16)),
                ('expire_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'email_and_code',
                'verbose_name_plural': 'emails_and_codes',
            },
        ),
    ]
